use databassignment;
create table Member1 (member_id int(5) primary key,member_name varchar(30),mamber_address varchar(50),acc_open_date Date, Membership_type varchar(20),penalty_amount int(7));
create table books1(book_no int(6),book_name varchar(30),author_name varchar(30),cost int(7),category char(10));
create table Issue (lib_issue_id int(10), book_no int(6),member_id int(5),issue_date Date,return_date Date);
desc Member1;
desc books1;
desc Issue;
alter table Member1 drop column penalty_amount;
desc Member1;
insert into Member1 values (1,'richa sharma','pune','2020-05-12','lifetime');
insert into Member1 values (2,'garima sen','pune',curdate(),'lifetime');
select * from Member1;
update Member1 set Membership_type='Annual' where member_id=2; 
select * from Member1;
insert into Member1 values (3,'ram','pune','2020-05-11','lifetime');
insert into Member1 values (4,'shyam','pune','2020-05-10','lifetime');
insert into Member1 values (5,'shree','pune','2020-05-9','lifetime');
insert into books1 values (101,'let us c','Dennies Ritchie',450,'system');
insert into books1 values (102,'Oracle – Complete Ref','Loni',550,'system');
insert into books1 values (103,'Mastering SQL','Loni',250,'system');
insert into books1 values (104,'PL SQL-Ref','ScottUrman',750,'system');
desc books1;
select * from books1;
delete from books1 where book_no=101;
select * from books1;
delete from books1 where book_no=102;
insert into books1 values (101,'let us c','Dennies Ritchie',450,'system');
update books1 set cost=300 ,category='RDBMS' where book_no=103 ;
drop table issue;
show tables;

select * from books;
delete from books where book_no=7001;
create table Issue (Lib_issue_id int,Book_no int,Member_Id int,Issue_Date Date,return_date Date);
insert into Issue(Lib_issue_id,Book_no,Member_Id,Issue_Date) values (7001,101,1,'2020-05-9');
select * from Issue;
select * from member1;
alter table member1 add salary int(10) not null;
select * from member1;